/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ptithcm.pe.views.login;

import com.ptithcm.pe.dao.UserDAO;
import com.ptithcm.pe.model.User;
import com.ptithcm.pe.utilities.Constraints;
import com.ptithcm.pe.utilities.MailUtilities;

import javax.swing.JOptionPane;

import com.ptithcm.pe.utilities.PasswordUtilities;
import com.ptithcm.pe.utilities.ValidationUtilities;
import org.apache.commons.lang3.RandomStringUtils;

/**
 * @author tezca
 */
public class SetNewPassword extends javax.swing.JFrame {
    private static String emailTo;
    private static ForgotPassword forgotPassword;
    private static User user;

    /**
     * Creates new form SetNewPassword2
     */
    public SetNewPassword(String emailTo, ForgotPassword forgotPassword, User user) {
        SetNewPassword.emailTo = emailTo;
        SetNewPassword.forgotPassword = forgotPassword;
        SetNewPassword.user = user;
        initComponents();
        setSize(600, 450);

        setDefaultCloseOperation(Login.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setExtendedState(Login.NORMAL);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        separator1 = new javax.swing.JSeparator();
        lblNewPassword = new javax.swing.JLabel();
        txtNewPassword = new javax.swing.JPasswordField();
        lblConfirm = new javax.swing.JLabel();
        txtConfirm = new javax.swing.JPasswordField();
        lblVerCode = new javax.swing.JLabel();
        txtVerCode = new javax.swing.JTextField();
        btnSendVerCode = new javax.swing.JButton();
        lblMessage = new javax.swing.JLabel();
        separator2 = new javax.swing.JSeparator();
        btnConfirm = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 0, 153));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText(Constraints.TITLE_CHANGE_PASSWORD);
        lblTitle.setPreferredSize(new java.awt.Dimension(388, 50));

        lblNewPassword.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblNewPassword.setText("Mật khẩu mới:");
        lblNewPassword.setPreferredSize(new java.awt.Dimension(125, 35));

        txtNewPassword.setPreferredSize(new java.awt.Dimension(170, 35));

        lblConfirm.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblConfirm.setText("Xác nhận mật khẩu:");
        lblConfirm.setPreferredSize(new java.awt.Dimension(125, 35));

        txtConfirm.setPreferredSize(new java.awt.Dimension(170, 35));

        lblVerCode.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblVerCode.setText("Nhập mã xác thực:");
        lblVerCode.setPreferredSize(new java.awt.Dimension(125, 35));

        txtVerCode.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtVerCode.setPreferredSize(new java.awt.Dimension(170, 35));

        btnSendVerCode.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSendVerCode.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon_captcha20.png"))); // NOI18N
        btnSendVerCode.setText("Gửi mã ");
        btnSendVerCode.setPreferredSize(new java.awt.Dimension(125, 35));
        btnSendVerCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendVerCodeActionPerformed(evt);
            }
        });

        lblMessage.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMessage.setText(Constraints.MESSAGE_SEND_CONFIRMATION_CODE_BEFORE);

        separator2.setPreferredSize(new java.awt.Dimension(588, 10));

        btnConfirm.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnConfirm.setText("Xác nhận");
        btnConfirm.setPreferredSize(new java.awt.Dimension(100, 30));
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        btnCancel.setText("Hủy");
        btnCancel.setPreferredSize(new java.awt.Dimension(100, 30));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(separator1)
                            .addComponent(separator2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblVerCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtVerCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSendVerCode, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(separator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVerCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVerCode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSendVerCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblMessage)
                .addGap(18, 18, 18)
                .addComponent(separator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(103, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendVerCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendVerCodeActionPerformed
        String code = RandomStringUtils.randomAlphanumeric(6);
        if (MailUtilities.sendEmail(emailTo, "Yêu cầu thay đổi mật khẩu", "Mã đặt lại mật khẩu: ", code)) {
            JOptionPane.showMessageDialog(this, Constraints.CP_SEND_CONFIRMATION_CODE_SUCCESS, Constraints.LABEL_INFORMATION, JOptionPane.INFORMATION_MESSAGE);
            lblMessage.setText(Constraints.MESSAGE_SEND_CONFIRMATION_CODE_ALTER);
        } else
            JOptionPane.showMessageDialog(this, Constraints.CP_SEND_CONFIRMATION_CODE_FAIL, Constraints.LABEL_ERROR, JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_btnSendVerCodeActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        String password = new String(txtNewPassword.getPassword());
        String confirm = new String(txtConfirm.getPassword());
        String newPassword = PasswordUtilities.toSha1(password);
        String oldPassword = user.getPassword();
        String code = txtVerCode.getText();

        if (password.isEmpty()) {
            JOptionPane.showMessageDialog(this, Constraints.CP_PASSWORD_EMPTY, Constraints.LABEL_ERROR, JOptionPane.ERROR_MESSAGE);
        } else if (confirm.isEmpty()) {
            JOptionPane.showMessageDialog(this, Constraints.CP_CONFIRM_PASSWORD_EMPTY, Constraints.LABEL_ERROR, JOptionPane.ERROR_MESSAGE);
        } else if (password.length() < 6 || password.length() > 20) {
            JOptionPane.showMessageDialog(this, Constraints.CP_PASSWORD_SHORT, Constraints.LABEL_ERROR, JOptionPane.ERROR_MESSAGE);
        } else if (!ValidationUtilities.checkPasswordValid(password)) {
            JOptionPane.showMessageDialog(this, Constraints.CP_PASSWORD_INVALID, Constraints.LABEL_ERROR, JOptionPane.ERROR_MESSAGE);
        } else if (!password.equals(confirm)) {
            JOptionPane.showMessageDialog(this, Constraints.CP_CONFIRM_PASSWORD_MISMATCH, Constraints.LABEL_ERROR, JOptionPane.ERROR_MESSAGE);
        } else if (code.isEmpty()) {
            JOptionPane.showMessageDialog(this, Constraints.CP_CONFIRMATION_CODE_EMPTY, Constraints.LABEL_ERROR, JOptionPane.ERROR_MESSAGE);
        } else if (!code.equals(MailUtilities.getCode())) {
            JOptionPane.showMessageDialog(this, Constraints.CP_CONFIRMATION_CODE_MISMATCH, Constraints.LABEL_ERROR, JOptionPane.ERROR_MESSAGE);
        } else if (oldPassword.equals(newPassword)) {
            JOptionPane.showMessageDialog(this, Constraints.CP_PASSWORD_IS_DUPLICATED, Constraints.LABEL_ERROR, JOptionPane.ERROR_MESSAGE);
        } else {
            String hashPassword = PasswordUtilities.toSha1(password);
            user.setPassword(hashPassword);
            int result = UserDAO.getInstance().update(user);
            if (result > 0) {
                JOptionPane.showMessageDialog(this, Constraints.CP_CHANGE_PASSWORD_SUCCESS, Constraints.LABEL_INFORMATION, JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
                forgotPassword.dispose();
                new Login().setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, Constraints.CP_CHANGE_PASSWORD_ERROR, Constraints.LABEL_ERROR, JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        forgotPassword.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SetNewPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SetNewPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SetNewPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SetNewPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SetNewPassword(emailTo, forgotPassword, user).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnSendVerCode;
    private javax.swing.JLabel lblConfirm;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblNewPassword;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblVerCode;
    private javax.swing.JSeparator separator1;
    private javax.swing.JSeparator separator2;
    private javax.swing.JPasswordField txtConfirm;
    private javax.swing.JPasswordField txtNewPassword;
    private javax.swing.JTextField txtVerCode;
    // End of variables declaration//GEN-END:variables
}
